SCFT-RBM: MatlabDocMaker Class Reference
MatlabDocMaker Class Reference
MatlabDocMaker: Automated documentation creation using doxygen and mtoc++ from within MatLab.
Static Public Member Functions
static function char name = getProjectName ()
Returns the project name.
static function char dir = getOutputDirectory ()
Returns the directory where the applications source files reside.
static function char dir = getSourceDirectory ()
Returns the directory where the applications source files reside.
static function char dir = getConfigDirectory ()
Returns the directory where the applications documentation configuration files reside.
static function char desc = getProjectDescription ()
Returns the short project description.
static function setProjectDescription (char value)
Sets the project description.
static function char version = getProjectVersion ()
Returns the current version of the project.
static function setProjectVersion (char value)
Sets the project version.
static function fullPath = getProjectLogo ()
Returns the logo image file for the project. Either an absolute path or a plain filename. For the latter case the image file is assumed to reside inside the directory returned by MatlabDocMaker.getConfigDirectory.
static function setProjectLogo (char value)
Sets the project logo. Set to ' to unset.
static function open ()
Opens the generated documentation.
static function create (varargin)
Creates the Doxygen documentation.
static function setup ()
Runs the setup script for MatlabDocMaker and collects all necessary paths in order for the documentation creation to work properly.
Static Public Attributes
static const ::char DOXYFILE_TEMPLATE = "Doxyfile.template"
File name for the doxygen configuration file processed by the MatlabDocMaker.
static const ::char LATEXEXTRAS_TEMPLATE = "latexextras.template"
File name for the latex extras style file processed by the MatlabDocMaker.
static const ::char MTOCPP_CONFIGFILE = "mtocpp.conf"
File name the mtoc++ configuration file.
Static Private Member Functions
static function value = getProjPrefTag ()
Gets the tag for the MatLab preferences struct.
static function value = getPref (name, default)
static function value = setPref (name, value)
Detailed Description
MatlabDocMaker: Automated documentation creation using doxygen and mtoc++ from within MatLab.
Currently documentation creation for unix and windows environment is supported.
Prerequisites
The following tools must be installed and present on the PATH or reside inside the folder returned by MatlabDocMaker.getConfigDirectory.
mtocpp, mtocpp_post (the main tool)
doxygen (mtoc++ is a filter for doxygen)
Strongly recommended
latex Doxygen supports built-in latex formulas and MatlabDocMaker/mtoc++ allows for easy extra latex inclusions and notation in code
dot Doxygen creates really nice inheritance graphs and collaboration diagrams with dot.
Author
Daniel Wirtz
Date
2011-10-13
Change in 1.5:
(Daniel Wirtz, 2013-12-03) Fixed default value selection for properties, now not having set a description or logo does not cause an error to be thrown.
Change in 1.5:
(Daniel Wirtz, 2013-02-21) Fixed the callback for suggested direct documentation creation after MatlabDocMaker.setup (Thanks to Aurelien Queffurust)
Change in 1.5:
(Daniel Wirtz, 2013-02-12) Also added the escaping for the Logo file. Thanks to Chris Olien for the hint.
Change in 1.5:
(Daniel Wirtz, 2013-01-07) Included some backslash escaping for paths on windows platforms. Thanks to MathWorks Pilot Engineer 'Arvind Jayaraman' for providing the feedback and code!
Change in 1.4:
(Daniel Wirtz, 2012-10-18) Removed m4 dependency and included constant properties for configuration file names.
New in 1.4:
(Daniel Wirtz, 2012-10-16)
Added two more configuration variables "ProjectDescription" and "ProjectLogo" for easier configuration of the MatlabDocMaker in many cases. Thanks to Wolfgang Mennerich http://www.mathworks.com/matlabcentral/fileexchange/authors/272859 for the suggestion.
Restructured the configuration, now only the project name function has to be implemented (the preferences tag depends on it, there might be more than one project within the same Matlab installation whos documentation is created using this tool). The rest can be provided either at setup time or later via suitable setters for the version, description and logo.
Automatically setting HaveDot in the doxygen config whenever its found on the environment path.
Added basic support for LaTeX documentation creation. Using the parameter latex=true for the create method creates the LaTeX version of the documentation in a folder "latex" in the OutputDirectory (default behaviour)
Change in 1.4:
(Daniel Wirtz, 2012-09-27) Added automatic dot Graphviz tool detection on call to create.
Change in 1.3:
(Daniel Wirtz, 2012-02-16)
Now also collecting error messages from mtocpp_post and adding them to the warnings.log file.
Added the directive "LD_LIBRARY_PATH= " for unix systems, as MatLab sets it inside its executing environment. This can lead to errors if doxygen and/or mtoc++ have been built using never GLIBC (libstd) versions than the one shipped with MatLab.
Change in 1.3:
(Daniel Wirtz, 2012-01-16)
Properly using the correct file separators everywhere now
Hyperlinked the log file so it can be opened directly
Change in 1.3:
(Daniel Wirtz, 2012-01-14) Not displaying the "generated warnings"-text if there have not been any during documentation creation.
Change in 1.2:
(Daniel Wirtz, 2011-11-27)
Included documentation creation for the Windows platform and combined the old methods into one (small effective differences)
No longer storing the doxygen binary file in the prefs as a lot of tools must be present on the path anyways. The new paradigm is to expect all required 3rd-party programmes to be available on PATH. As backup the configuration files directory is added to the Matlab PATH environment nonpermanently and any executables found there will thus also be usable.
Included checks for dot and latex at the setup stage to recommend installation of those tools if not present (the default doxygen settings in Doxyfile.m4 are to use both)
Change in 1.2:
(Daniel Wirtz, 2011-11-08) Improved the createUnix method by displaying the warnings and writing the output to a log file afterwards. Not using cprintf anymore as this is 3rd party software.
Change in 1.2:
(Daniel Wirtz, 2011-11-07) Fixed a recursion bug caused by copy and paste. Now the preferences are stored on an per-application basis.
Change in 1.2:
(Daniel Wirtz, 2011-11-04) Changed the name to MatlabDocMaker in order to export it into the mtoc++ distribution later.
New in 1.2:
(Daniel Wirtz, 2011-10-13) Added this class and moved documentation related stuff here from the KerMor class.
This class is part of the mtoc++ tool
Homepage http://www.morepas.org/software/mtocpp/
License http://www.morepas.org/software/mtocpp/docs/licensing.html
Copyright (c) 2012, Daniel Wirtz All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file MatlabDocMaker.m.
Member Function Documentation
function MatlabDocMaker.create (varargin) static
Creates the Doxygen documentation.
Parameters
varargin Optional parameters for creation.
create ([ "open", open_value ] [, "latex", latex_value ])
Named Parameters for varargin:
open Set to true if the documentation should be opened after successful compilation Default: false
latex Set to true if output should be generated, too. Default: false
Definition at line 412 of file MatlabDocMaker.m.
References DOXYFILE_TEMPLATE, getConfigDirectory(), getOutputDirectory(), getProjectDescription(), getProjectLogo(), getProjectName(), getProjectVersion(), getSourceDirectory(), LATEXEXTRAS_TEMPLATE, MTOCPP_CONFIGFILE, and open().
function char dir = MatlabDocMaker.getConfigDirectory () static
Returns the directory where the applications documentation configuration files reside.
This folder must contain at least the files "mtoc.conf" and "Doxyfile.template"
Return values
dir The documentation configuration directory
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 225 of file MatlabDocMaker.m.
References getPref().
Referenced by create(), getProjectLogo(), and setProjectLogo().
function char dir = MatlabDocMaker.getOutputDirectory () static
Returns the directory where the applications source files reside.
Return values
dir The output directory
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 195 of file MatlabDocMaker.m.
References getPref().
Referenced by create(), and open().
static function value = MatlabDocMaker.getPref (name, default) static private
Definition at line 782 of file MatlabDocMaker.m.
References getProjPrefTag().
Referenced by getConfigDirectory(), getOutputDirectory(), getProjectDescription(), getProjectLogo(), getProjectVersion(), getSourceDirectory(), and setup().
function char desc = MatlabDocMaker.getProjectDescription () static
Returns the short project description.
See also
setProjectDescription
Return values
desc The short project description
Default:
[]
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 244 of file MatlabDocMaker.m.
References getPref().
Referenced by create().
function fullPath = MatlabDocMaker.getProjectLogo () static
Returns the logo image file for the project. Either an absolute path or a plain filename. For the latter case the image file is assumed to reside inside the directory returned by MatlabDocMaker.getConfigDirectory.
See also
setProjectLogo
Return values
logoFile The projects logo image file.
Default:
[]
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 317 of file MatlabDocMaker.m.
References getConfigDirectory(), and getPref().
Referenced by create().
function char name = MatlabDocMaker.getProjectName () static
Returns the project name.
Note
Changing the return value of this method will require another execution of MatlabDocMaker.setup as the preferences storage key also depends on it.
Return values
name The project name
Definition at line 170 of file MatlabDocMaker.m.
Referenced by create(), getProjPrefTag(), and setup().
function char version = MatlabDocMaker.getProjectVersion () static
Returns the current version of the project.
Note
The built-in @new and @change tags from the Doxyfile.template support two-level versioning a la X.X.
See also
setProjectVersion
Return values
version The project version
Default:
[]
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 279 of file MatlabDocMaker.m.
References getPref().
Referenced by create().
function value = MatlabDocMaker.getProjPrefTag () static private
Gets the tag for the MatLab preferences struct.
Change in 0.7:
(Daniel Wirtz, 2013-04-02) Now also removing "~" and "-" characters from ProjectName tags for preferences.
Definition at line 769 of file MatlabDocMaker.m.
References getProjectName().
Referenced by getPref(), and setPref().
function char dir = MatlabDocMaker.getSourceDirectory () static
Returns the directory where the applications source files reside.
Return values
dir The project source directory
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 210 of file MatlabDocMaker.m.
References getPref().
Referenced by create().
function MatlabDocMaker.open () static
Opens the generated documentation.
Depending on the systems type the generated index.html is opened in the systems default browser.
Definition at line 391 of file MatlabDocMaker.m.
References getOutputDirectory().
Referenced by create().
static function value = MatlabDocMaker.setPref (name, value) static private
Definition at line 795 of file MatlabDocMaker.m.
References getProjPrefTag().
Referenced by setProjectDescription(), setProjectLogo(), setProjectVersion(), and setup().
function MatlabDocMaker.setProjectDescription (char value) static
Sets the project description.
See also
getProjectDescription
Parameters
value The description
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 260 of file MatlabDocMaker.m.
References setPref().
function MatlabDocMaker.setProjectLogo (char value) static
Sets the project logo. Set to ' to unset.
See the doxygen documentation for valid logo file types (wont be checked here).
See also
getProjectLogo
Parameters
value The logo file to use. Must be either an absolute path or a plain filename, in which case the image is assumed to reside inside the MatlabDocMaker.getConfigDirectory directory.
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 347 of file MatlabDocMaker.m.
References getConfigDirectory(), and setPref().
Referenced by setup().
function MatlabDocMaker.setProjectVersion (char value) static
Sets the project version.
See also
getProjectVersion
Parameters
value The version string
Note
This method has the MATLAB method attribute Sealed set to true. It cannot be overwritten.
matlab documentation of method attributes.
Definition at line 298 of file MatlabDocMaker.m.
References setPref().
function MatlabDocMaker.setup () static
Runs the setup script for MatlabDocMaker and collects all necessary paths in order for the documentation creation to work properly.
Definition at line 631 of file MatlabDocMaker.m.
References getPref(), getProjectName(), setPref(), and setProjectLogo().
Member Data Documentation
MatlabDocMaker.DOXYFILE_TEMPLATE = "Doxyfile.template" static
File name for the doxygen configuration file processed by the MatlabDocMaker.
Assumed to reside in the MatlabDocMaker.getConfigDirectory
Default: Doxyfile.template
Definition at line 130 of file MatlabDocMaker.m.
Referenced by create().
MatlabDocMaker.LATEXEXTRAS_TEMPLATE = "latexextras.template" static
File name for the latex extras style file processed by the MatlabDocMaker.
Assumed to reside in the MatlabDocMaker.getConfigDirectory. If not found, no latex extras are used.
Default: latexextras.template
Definition at line 142 of file MatlabDocMaker.m.
Referenced by create().
MatlabDocMaker.MTOCPP_CONFIGFILE = "mtocpp.conf" static
File name the mtoc++ configuration file.
Assumed to reside in the MatlabDocMaker.getConfigDirectory. If not found, no special configuration is used.
Default: mtocpp.conf
Definition at line 155 of file MatlabDocMaker.m.
Referenced by create().
The documentation for this class was generated from the following file:
tools/MatlabDocMaker.m