SCFT-RBM: examples/chapter4/shared/stability.m File Reference
stability.m File Reference
This script calculates the inf-sup-constant and the bound for this constant given in Section 4.2.
Functions
function stability ()
This script calculates the inf-sup-constant and the bound for this constant given in Section 4.2.
Detailed Description
This script calculates the inf-sup-constant and the bound for this constant given in Section 4.2.
Definition in file stability.m.
Function Documentation
function stability ()
This script calculates the inf-sup-constant and the bound for this constant given in Section 4.2.
Definition at line 17 of file stability.m.
References computeMinMaxEv().
Referenced by ch4ex1_run(), ch4ex2_run(), and ch4ex3_run().